### ISSUE TITLE
Error running scvh_filter_matrix.r

### ISSUE THREAD

**Issue by malonzm1** [holab-hku/Vulture#2]
Hi,

When running scvh_filter_matrix.r I get the following error:

Sig     FALSE TRUE
  FALSE  1915    0
  TRUE     42 5850
Analyze bam in /scratch/cs/pan-autoimmune/data/vulture/scRNAseq/GSE215237/SRR21863020
Getting the barcodes of the non-host genes that have potential interaction with host [Mon Sep 18 13:18:12 EEST 2023]
gene: gene-PestiV1gp1
bcs: CTGGTCTAGAAGGCCT

/scratch/cs/pan-autoimmune/data/vulture/scRNAseq/GSE215237/SRR21863020/alignment_outs/Aligned.sortedByCoord.out.bam is not present or is empty
Looping over STARsolo BAM file to store host read IDS and output non-host BAM [Mon Sep 18 13:18:14 EEST 2023]

Please advise.

Thanks and good day.

**Comment by hiyin** [comment]
@juychen

**Comment by juychen** [comment]
> Hi,
> 
> When running scvh_filter_matrix.r I get the following error:
> 
> Sig FALSE TRUE FALSE 1915 0 TRUE 42 5850 Analyze bam in /scratch/cs/pan-autoimmune/data/vulture/scRNAseq/GSE215237/SRR21863020 Getting the barcodes of the non-host genes that have potential interaction with host [Mon Sep 18 13:18:12 EEST 2023] gene: gene-PestiV1gp1 bcs: CTGGTCTAGAAGGCCT
> 
> /scratch/cs/pan-autoimmune/data/vulture/scRNAseq/GSE215237/SRR21863020/alignment_outs/Aligned.sortedByCoord.out.bam is not present or is empty Looping over STARsolo BAM file to store host read IDS and output non-host BAM [Mon Sep 18 13:18:14 EEST 2023]
> 
> Please advise.
> 
> Thanks and good day.

Sorry for my late reply, what files are in your alignment_outs folder?

**Comment by malonzm1** [comment]
Thanks.

        4096	9/18/23 12:47	_STARgenome
11600494733	9/18/23 12:58	Aligned.out.bam
        4096	9/18/23 12:58	Solo.out
    9254511	9/18/23 12:58	SJ.out.tab
        1308	9/18/23 12:59	Log.progress.out
      52278	9/18/23 12:59	Log.out
        2037	9/18/23 12:59	Log.final.out

**Comment by juychen** [comment]
> Thanks.
> 
>         4096 9/18/23 12:47 _STARgenome 11600494733 9/18/23 12:58 Aligned.out.bam         4096 9/18/23 12:58 Solo.out     9254511 9/18/23 12:58 SJ.out.tab         1308 9/18/23 12:59 Log.progress.out       52278 9/18/23 12:59 Log.out         2037 9/18/23 12:59 Log.final.out

Seems that you did not get the sorted bam file.

did you set --outSAMtype "BAM SortedByCoordinate" when runing alignment using scvh_map_reads.pl?

**Comment by malonzm1** [comment]
Thanks!
